### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'weights/aggregation_network.pt'

### ISSUE THREAD

**Issue by 3202336152** [diffusion-hyperfeatures/diffusion_hyperfeatures#1]
First of all, thank you very much for your work. You've done an excellent job.I would like to ask if you can give the file of this weight. weights/aggregation_network.pt.

**Comment by g-luo** [comment]
Hi! Thanks for your kind comments. You can download the weights from our servers. In the root folder `diffusion_hyperfeatures`, run:

```
mkdir weights
wget http://diffusion_hyperfeatures.berkeleyvision.org/weights/aggregation_network.pt -O weights/aggregation_network.pt
```
