### ISSUE TITLE
Timeout when downloading the weights

### ISSUE THREAD

**Issue by frouhi** [diffusion-hyperfeatures/diffusion_hyperfeatures#10]
Thanks for sharing your great work.
I've been trying to download the weights, but it keeps timing out. I though to check if the hosting is still up, and if they are hosted anywhere else I can access?

Thanks

**Comment by g-luo** [comment]
Hi @frouhi, thank you for raising this issue -- our self-hosted server went down. I went ahead and uploaded the weights to a [huggingface repo](https://huggingface.co/g-luo/diffusion-hyperfeatures), where all the paths in this main repo are also updated to point to these new weights.
