### ISSUE TITLE
where is the codes for training?

### ISSUE THREAD

**Issue by guaiguaide1** [diffusion-hyperfeatures/diffusion_hyperfeatures#2]
Hello, when will the training code be released? Looking forward to learning from your code.

**Comment by g-luo** [comment]
Hi, thanks for your patience. You can find the training code here: https://github.com/diffusion-hyperfeatures/diffusion_hyperfeatures/blob/main/train_hyperfeatures.py. Please also read the associated README section before getting started: https://github.com/diffusion-hyperfeatures/diffusion_hyperfeatures#training.
