### ISSUE TITLE
Pre-trained weights for aggregration network

### ISSUE THREAD

**Issue by danielajisafe** [diffusion-hyperfeatures/diffusion_hyperfeatures#3]
Thank you so much Grace Luo for the amazing work! 

Please are the pre-trained weights for the aggregation network made available, or perhaps a small script for training the network? 

Thanks

**Comment by g-luo** [comment]
Hi @danielajisafe, thanks for your message! You can find instructions for downloading the weights here: https://github.com/diffusion-hyperfeatures/diffusion_hyperfeatures/issues/1.

**Comment by danielajisafe** [comment]
Thank you so much Grace and for your prompt response!

**Comment by danielajisafe** [comment]
I also see the stable diffusion model (aggregation_network_sdv2-1.pt) is provided on the same server, which is also helpful. Thanks again.
