### ISSUE TITLE
Training script for the aggregation network

### ISSUE THREAD

**Issue by danielajisafe** [diffusion-hyperfeatures/diffusion_hyperfeatures#4]
Hi Grace, 

Thank you for sharing.  Please can you provide the training script for the aggregation network? Thanks again.

**Comment by g-luo** [comment]
Hi, please see: https://github.com/diffusion-hyperfeatures/diffusion_hyperfeatures/issues/2.

**Comment by danielajisafe** [comment]
Thanks.
